name: Sync GitLab to GitHub

on:
  schedule:
    - cron: '0 16 * * *' # Runs daily at midnight UTC+8
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  Pull_from_GitLab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git config pull.rebase true
      
      - name: Pull the latest change
        run: |
          git fetch origin ${{ github.ref }}
          git merge -X theirs --allow-unrelated-histories --no-ff origin/main
          
      - name: Pull from GitLab
        run: |
          git remote add gitlab ${{ secrets.GITLAB_REPO_URL }}
          git fetch gitlab
          git merge -X theirs --allow-unrelated-histories --no-ff gitlab/main

      - name: Push to GitHub
        run: |
          git fetch origin
          git push origin main
